/**
 * AyeZee CMS Helper - Build-Time Cached Version
 *
 * Place this file in: src/lib/ayezee-cms-helper.ts
 *
 * This reads from the cms-cache.json file generated by the Astro integration.
 */

// Import the cached data (generated by the integration)

import cmsData from "../data/cms-cache.json";

// Types
export interface ModuleField {
  key: string;
  label: string;
  fieldType: string;
  required?: boolean;
  options?: unknown[];
  validation?: unknown;
}

export interface CachedModule {
  id: string;
  instanceKey: string;
  label: string;
  slug: string;
  dataType: "collection" | "singleton" | "submissions";
  category: string;
  description?: string;
  icon?: string;
  fields: ModuleField[];
  isActive: boolean;
  sortOrder: number;
  data: ModuleDataItem[];
  pagination: {
    total: number;
    limit?: number | null;
    offset?: number;
    count: number;
  };
  parameters: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface ModuleDataItem {
  id: string;
  data: Record<string, unknown>;
  sortOrder?: number;
  status?: string;
  ipAddress?: string;
  userAgent?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface CMSCache {
  project: {
    id: string;
    slug: string;
    name: string;
    domain?: string;
  };
  modules: CachedModule[];
  fetchedAt: string;
  version: string;
}

const cache = cmsData as CMSCache;

/**
 * Get project information
 */
export function getProject() {
  return cache.project;
}

/**
 * Get all modules
 */
export function getModules(): CachedModule[] {
  return cache.modules;
}

/**
 * Get a module by its instance key
 */
export function getModule(instanceKey: string): CachedModule | null {
  return cache.modules.find((mod) => mod.instanceKey === instanceKey) || null;
}

/**
 * Get a module by its label (case-insensitive)
 * Example: getModuleByLabel("Photo Gallery")
 */
export function getModuleByLabel(label: string): CachedModule | null {
  const normalizedLabel = label.toLowerCase();
  return cache.modules.find((mod) => mod.label.toLowerCase() === normalizedLabel) || null;
}

/**
 * Get a module by its slug
 * Example: getModuleBySlug("photo-gallery")
 */
export function getModuleBySlug(slug: string): CachedModule | null {
  return cache.modules.find((mod) => mod.slug === slug) || null;
}

/**
 * Get modules by category
 */
export function getModulesByCategory(category: string): CachedModule[] {
  return cache.modules.filter((mod) => mod.category === category);
}

/**
 * Get modules by data type
 */
export function getModulesByDataType(
  dataType: "collection" | "singleton" | "submissions"
): CachedModule[] {
  return cache.modules.filter((mod) => mod.dataType === dataType);
}

/**
 * Get all form modules (submissions type)
 */
export function getForms(): CachedModule[] {
  return getModulesByDataType("submissions");
}

/**
 * Get all content collections
 */
export function getCollections(): CachedModule[] {
  return getModulesByDataType("collection");
}

/**
 * Get all singleton content
 */
export function getSingletons(): CachedModule[] {
  return getModulesByDataType("singleton");
}

/**
 * Get data from a module by instance key
 */
export function getModuleData(instanceKey: string): ModuleDataItem[] {
  const foundModule = getModule(instanceKey);
  return foundModule?.data || [];
}

/**
 * Get data from a module by label
 */
export function getModuleDataByLabel(label: string): ModuleDataItem[] {
  const foundModule = getModuleByLabel(label);
  return foundModule?.data || [];
}

/**
 * Get data from a module by slug
 */
export function getModuleDataBySlug(slug: string): ModuleDataItem[] {
  const foundModule = getModuleBySlug(slug);
  return foundModule?.data || [];
}

/**
 * Submit data to a form module (submissions type)
 * This still requires a runtime API call
 */
export async function submitForm(
  instanceKey: string,
  formData: Record<string, unknown>
): Promise<{
  success: boolean;
  submissionId?: string;
  message?: string;
}> {
  const apiKey = import.meta.env.PUBLIC_AYEZEE_API_KEY;
  const cmsDomain = import.meta.env.PUBLIC_CMS_DOMAIN;
  const projectSlug = import.meta.env.PUBLIC_PROJECT_SLUG;

  if (!apiKey) {
    return {
      success: false,
      message: "PUBLIC_AYEZEE_API_KEY environment variable is required",
    };
  }

  try {
    let domain = cmsDomain;
    if (!domain.startsWith("http://") && !domain.startsWith("https://")) {
      const protocol = domain.includes("localhost") ? "http" : "https";
      domain = `${protocol}://${domain}`;
    }

    const url = `${domain}/api/v1/projects/${projectSlug}/submit/${instanceKey}`;

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify(formData),
    });

    if (!response.ok) {
      throw new Error(`API error: ${response.status} ${response.statusText}`);
    }

    const result = await response.json();

    if (!result.success) {
      throw new Error(result.message || "Form submission failed");
    }

    return {
      success: true,
      submissionId: result.data?.id,
      message: "Form submitted successfully",
    };
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : "Form submission failed",
    };
  }
}

/**
 * Submit to a form by label
 */
export async function submitFormByLabel(
  label: string,
  formData: Record<string, unknown>
): Promise<{
  success: boolean;
  submissionId?: string;
  message?: string;
}> {
  const formModule = getModuleByLabel(label);
  if (!formModule) {
    return {
      success: false,
      message: `Form module with label "${label}" not found`,
    };
  }
  return submitForm(formModule.instanceKey, formData);
}

/**
 * Get metadata about when the cache was last updated
 */
export function getCacheInfo() {
  return {
    fetchedAt: cache.fetchedAt,
    version: cache.version,
    moduleCount: cache.modules.length,
  };
}

/**
 * Get Turnstile configuration for a form module
 */
export function getTurnstileConfig(moduleIdentifier: string): {
  enabled: boolean;
  siteKey: string | null;
} {
  // Try to find module by instance key, label, or slug
  let module = getModule(moduleIdentifier);
  if (!module) {
    module = getModuleByLabel(moduleIdentifier);
  }
  if (!module) {
    module = getModuleBySlug(moduleIdentifier);
  }

  if (!module || !module.parameters?.turnstile) {
    return { enabled: false, siteKey: null };
  }

  const turnstile = module.parameters.turnstile as any;
  return {
    enabled: turnstile.enabled === true,
    siteKey: turnstile.siteKey || null,
  };
}

/**
 * Check if a form has Turnstile enabled
 */
export function isTurnstileEnabled(moduleIdentifier: string): boolean {
  const config = getTurnstileConfig(moduleIdentifier);
  return config.enabled && config.siteKey !== null;
}

/**
 * Get form configuration including all settings
 */
export function getFormConfig(moduleIdentifier: string): {
  module: CachedModule | null;
  turnstile: {
    enabled: boolean;
    siteKey: string | null;
  };
  apiUrl: string;
  apiKey: string;
} {
  // Try to find module by instance key, label, or slug
  let module = getModule(moduleIdentifier);
  if (!module) {
    module = getModuleByLabel(moduleIdentifier);
  }
  if (!module) {
    module = getModuleBySlug(moduleIdentifier);
  }

  const cmsDomain = import.meta.env.PUBLIC_CMS_DOMAIN || "http://localhost:3000";
  const projectSlug = import.meta.env.PUBLIC_PROJECT_SLUG || "";
  const apiKey = import.meta.env.PUBLIC_AYEZEE_API_KEY || "";

  let domain = cmsDomain;
  if (!domain.startsWith("http://") && !domain.startsWith("https://")) {
    const protocol = domain.includes("localhost") ? "http" : "https";
    domain = `${protocol}://${domain}`;
  }

  const apiUrl = module
    ? `${domain}/api/v1/projects/${projectSlug}/submit/${module.instanceKey}`
    : "";

  return {
    module,
    turnstile: getTurnstileConfig(moduleIdentifier),
    apiUrl,
    apiKey,
  };
}
